image: evilbeaver/onescript:1.0.21

stages:
  - test
  - build
  - deploy

test:
  stage: test
  script:
    - opm install 1testrunner
    - 1testrunner -runall ./tests
  artifacts:
    when: on_failure
    paths:
    - .
    expire_in: 1 day
    
build:
  stage: build
  script:
  - opm build . -mf packagedef -out .
  # - opm push --token $GITHUB_TOKEN --channel stable $CI_PROJECT_NAME-$CI_COMMIT_REF_NAME.ospx 
  artifacts:
    name: "$CI_PROJECT_NAME-$CI_COMMIT_REF_NAME"
    paths:
    - $CI_PROJECT_NAME-$CI_COMMIT_REF_NAME.ospx
  # only:
  #   - tags  

deploy to hub.oscript:
  stage: deploy
  variables:
    GIT_STRATEGY: none
  script:
  - opm push --token $GITHUB_TOKEN --channel stable $CI_PROJECT_NAME-$CI_COMMIT_REF_NAME.ospx 
  artifacts:
    when: on_failure
    paths:
    - .
    expire_in: 1 day
  # only:
  #   - tags