image: evilbeaver/onescript:1.0.19

stages:
  - test
  - build
  - deploy

test:
  stage: test
  script:
    - opm install 1testrunner
    - 1testrunner -runall ./tests
  artifacts:
    when: on_failure
    paths:
    - .
    expire_in: 1 day
    
build:
  stage: build
  script:
  # - grep '%ver' -P -R -I -l packagedef | xargs sed -i 's/%ver/'$CI_COMMIT_REF_NAME'/g'
  - mkdir ./build
  - opm build -m ./packagedef -o ./build  .
  artifacts:
    name: "$CI_PROJECT_NAME-$CI_COMMIT_REF_NAME"
    paths:
    - $CI_PROJECT_NAME-$CI_COMMIT_REF_NAME.ospx
  only:
    - tags  

deploy to hub.oscript:
  stage: deploy
  variables:
    GIT_STRATEGY: none
  script:
  - cd ./build
  - opm push --token $GITHUB_TOKEN --file $CI_PROJECT_NAME-$CI_COMMIT_REF_NAME --channel stable
  artifacts:
    when: on_failure
    paths:
    - .
    expire_in: 1 day
  only:
    - tags